### ISSUE TITLE
Command timeout

### ISSUE THREAD

**Issue by eknkc** [carlosabalde/libvmod-redis#11]
Hi,

I believe the built in timeout setting applies to connecting to servers. So, if the connection can not be established in xxx ms, the command will fail.

Is there any way to have a timeout for the actual execution of a command, even if the server connection looks healthy? Be it a slow eval, or a half open tcp connection due to a network issue.. I'm not 100% certain that the current implementation does not do that though. Just some simple experimentation with using `nc -l 6379` as a fake redis server that would never respond. `vmod-redis` seems to wait for an answer indefinitely.

Thanks.

**Comment by carlosabalde** [comment]
Hi,

Timeouts for command executions are not possible at the moment. The VMOD is based in the hiredis library, which currently does not include that feature. Luckily there is an [open issue](https://github.com/redis/hiredis/issues/306) exploring how to add that feature to the library. If that' finally implemented I'll add it to the VMOD asap.

**Comment by carlosabalde** [comment]
Version 0.2.4 has ben released including support for timeouts when executing commands. Now `redis.init()` also receives the default timeout when executing Redis commands and `redis.timeout()` allows settings different timeouts for specific command executions.
