### ISSUE TITLE
How to handle redis timeout or disconnect

### ISSUE THREAD

**Issue by razvanphp** [carlosabalde/libvmod-redis#21]
Hello,

First of all, thank you for this great extension. I got it all running, but for some historical reasons where connections got stuck in redis, we enabled `timeout 16` and `tcp-keepalive 60` in config, so the server closes idle connections.

What I get after some time in journalctl:
```
Nov 04 11:06:15 server varnishd[907]: [REDIS][redis_execute] Failed to execute Redis command (GET): [3] Server closed the connection
```
How can I prevent this? setting `connection_ttl` to a lower value would close and reopen the connection every time or just "tell" redis that the client is not idle?

Of course in the end I could just disable timeout again, but I'm afraid that when we really have networking problems or redis is restarted, we will have problems, since I don't know if the vmod tries to reconnect at least.

Currently we are building an API Gateway based on this, so we need to make sure this is rock solid.

Cheers!

**Comment by carlosabalde** [comment]
Hi,

I can think about a couple of options that may help in your scenario:

1. As you suggested, **you could use a low connection TTL**. When a connection reaches the TTL (i.e. after TTL seconds since it was created), it will be closed and a new connection will be created. Obviously, if you set a very low TTL, you may add too much overhead because you are creating/closing connections inteads of reusing them.

2. **You could set the number of retries to 1**. That way commands failed because of stalled connections will success when retring (once a connections enters in an error state is not reused anymore). Obviously in this case errors trigered during the first try will still be logged.

On the other hand, note that when the VMOD gets a Redis connection it allways checks if the connections is still valid before using it (https://github.com/carlosabalde/libvmod-redis/blob/4.1/src/core.c#L427-L435). If not, the connection is dropped and a new one created. It's possible to get those errors in certains cases but they shouldn't be common.

Hope this helps.

**Comment by razvanphp** [comment]
Now that I think about it, I find no real reason to keep the `timeout` option, as long as `tcp-keepalive` is enabled (not 0), I should not have hanging connections, right?

If I use a TTL in the vmod, the connections are still going to be closed and opened every time, something I want to avoid normally. On the other hand, I enabled connection reuse in the kernel, so I should not have a lot of TIME_WAIT connections on the servers.

Also if I set the retries to 1, what happens if redis is down for some time, when does he try to reconnect after the retries was reached?

I'm still not sure what solution to choose, to be as failure resistant as possible.

**Comment by carlosabalde** [comment]
We usually recommend settings a reasonable `tcp-keepalive` (e.g. 60 seconds) and keep Varnish and Redis as close as possible (e.g. same VLAN, etc.). 

About the behviour when Redis is down and retries is set to 1, executions will be always retried. I mean, let's assume you call `redis.execute()` but the execution cannot be completed for some reason (e.g. unable to get a connections, connection reset by peer, etc.). In that case the execution will be retried once.

**Comment by razvanphp** [comment]
So he tries one more time, fails again, and then what? Should I take care of this programmatically in VCL myself?

If `timeout` is set, there is no way for the vmod to tell redis "I'm still here, don't close the connection", right?

**Comment by carlosabalde** [comment]
Tries one more time, fails again, and then the control returns to VCL. In that case, `redis.replied()` will be `FALSE`.  Depending on you particular case you may want to handle those error cases in VCL somehow.

And yes, the VMOD does not implement any kind of pooling in the connection to keep it open. As previously commented, the thing the VMOD does with a connection is checking that is still alive before using it.

**Comment by razvanphp** [comment]
Thank you for your fast responses.

After further tests, I found out that with `shared_contexts` both enabled or disabled, connections to redis are closed and left in TIME_WAIT after each request, even tho varnish was not restarted.

I dont't even use `redis.fini();` in my config. My understanding is that `vcl_init` and `vcl_fini` are executed only when loading the vcl or restarting varnish.

In our case, given the high traffic, the pool of ports would be quickly filled up, so we need to reuse connections to redis. How can we achieve that?

**Comment by carlosabalde** [comment]
@razvanphp: I've an e-mail notification with some more questions from you but it seems that it has disappeared. Have you removed it?

**Comment by razvanphp** [comment]
Yes, sorry, it was my fault, php-fpm was doing those redis connections.

Just to make sure I got my tests right, the vmod will not open new connections to redis if not needed? For example I have now `shared_contexts = true` and `max_contexts = 50` but there is only one established connection between redis and varnish. If I use ab stress test for more concurrency, the other connections appear.

You mention in the wiki that one should make sure the pool is big enough, how can I know that? is there any warning in the logs? I could not trigger that even with 1 context... varnish and redis are really fast..

Thank you for your fast answers!

**Comment by carlosabalde** [comment]
Yes, connections are created only when needed. The only way to know the right value for `max_contexts` is doing stress testing and measuring response times. If your pool is too small, Varnish workers threads will be blocked waiting for connections when executing Redis commands and response time will increase.
