### ISSUE TITLE
Replace ad-hoc thread state by TASK_PRIV pointers

### ISSUE THREAD

**Issue by carlosabalde** [carlosabalde/libvmod-redis#22]
Replace ad-hoc thread state by ``TASK_PRIV`` pointers (4.1 branch) once PRIV pointers are available in VMOD object methods.

**Comment by carlosabalde** [comment]
Related: https://github.com/varnishcache/varnish-cache/issues/1800#issuecomment-243566969

**Comment by carlosabalde** [comment]
Same for PRIV_* pointers currently not available in VMOD objects.

**Comment by nigoroll** [comment]
just FYI, even with https://github.com/varnishcache/varnish-cache/pull/2061 we won't have
https://github.com/varnishcache/varnish-cache/wiki/VIP1:-PRIV_*-visibility-and-lifetime-control yet, so the priv pointers will still be per-vmod, not per-object. But at least they will be available, so until we have VIP1, you can do the per-vmod->per-object linkage yourself

**Comment by carlosabalde** [comment]
Thanks for the info! 👍

**Comment by carlosabalde** [comment]
@nigoroll, now that ``PRIV_TASK`` and ``PRIV_VCL`` can be accessed in object methods thanks to https://github.com/varnishcache/varnish-cache/pull/2061 I've been able to improve the implementation of the Redis VMOD slightly.

However, there is one case that still forces me to keep track of ``PRIV_VCL`` pointers in the implementation of the VMOD: when objects are destroyed the ``PRIV_VCL`` is not provided to the ``vmod_*__fini(...)`` callback. I can live with that but I'm mentioning it just in case having that could be useful to other VMOD developers :)

**Comment by nigoroll** [comment]
@carlosabalde I had a quick look at your code and failed to immediately understand what exactly you mean. All privs have a free callback which gets called when they go out of scope, and you're already making use of this with `free_vcl_state()`.
So can you please elaborate?

**Comment by carlosabalde** [comment]
I've been thinking about my own suggestion and now I see it's not really related with your PR. Just in case you're interested, the scenario is as follows:

- When a VMOD object is defined you need to implement a couple of callbacks. In this particular VMOD: ``vmod_db__init()`` and ``vmod_db__fini()``.

- Input parameters of [``vmod_db__init()``](https://github.com/carlosabalde/libvmod-redis/blob/master/src/vmod_redis.c#L375-L381) are [defined in the VCC file](https://github.com/carlosabalde/libvmod-redis/blob/master/src/vmod_redis.vcc#L65-L76). ``PRIV_VCL`` is allowed in there (it was previous to your PR), and that's very useful because that pointer is required in order to access to some data required when creating new object instances.

- However input parameters for [``vmod_db__fini()``](https://github.com/carlosabalde/libvmod-redis/blob/master/src/vmod_redis.c#L447-L448) cannot be defined. All you get is the object instance. However, this particular VMOD also needs access to ``PRIV_VCL`` during ``vmod_db__fini()`` in order to access to some shared data structures.

The way this is done at the moment is holding a reference to ``PRIV_VCL`` in all object instances. This reference is set during ``vmod_db__init()`` and it is used during ``vmod_db__fini()``. It was also used in all object methods where it was not possible to access to ``PRIV_VCL`` prior to your PR.

I was wondering if it would be possible to include ``PRIV_VCL`` as a parameter in ``vmod_db__fini()``. I though it could be useful for other VMOD developers, but now I see this is absolutely unrelated with your PR, so please, excuse me and forget this message :)

**Comment by nigoroll** [comment]
i'm not picky about context, understood now. Will have a look tomorrow

**Comment by nigoroll** [comment]
I hope to have cleared up my thoughts about this now:

Passing the `PRIV_VCL` to the destructor callback does not seem to provide any relevant benefit. It would only make sense for this `PRIV_VCL` anyway - `PRIV_CALL` on a `__fini` callback would just be useless and we're out-of-scope for `PRIV_TOP` and `PRIV_TASK.`

The object instance can contain everything required by the destructor, and while you need the `PRIV_VCL`, others may need whatever other parameter passed to the constructor.

I have not devoured your vmod completely, but it appears to me that you need to keep track of the db objects you created per vcl due to per-vcl connection pooling, is this correct? Otherwise I'd think that you could just have a simple 1:1 obj->db conn relation and wouldn't need to keep track of the db objects per vcl instance, right?

**Comment by carlosabalde** [comment]
Yes, references to all db objects are stored in ``PRIV_VCL`` for several reasons. For example, when a COLD event is triggered the VMOD needs access to all db objects in order to release connections. In any case, I agree this is not generic enough. Storing whatever you need during ``__fini`` when creating the object instance is the way to go. Thanks for your time!
