### ISSUE TITLE
Expose SHA1 function?

### ISSUE THREAD

**Issue by razvanphp** [carlosabalde/libvmod-redis#24]
I have an use-case where I need this in VCL, and it would not require the whole digest vmod compiled.

Thank you!

**Comment by carlosabalde** [comment]
I don't think the SHA-1 or CRC-16 implementations embedded in the VMOD should be exposed in its API. I understand you prefer to avoid requiring an additional VMOD for that, but that's definitely the way to go. I think adding that kind of stuff to the API of the Redis VMOD would be hacky and dirty.
