### ISSUE TITLE
Use Varnish locks instead of plain pthread mutexes

### ISSUE THREAD

**Issue by carlosabalde** [carlosabalde/libvmod-redis#26]
Replace pthread mutexes by Varnish locks (4.1 branch). References in libvmod-named by @Dridi:

  - https://github.com/Dridi/libvmod-named/commit/3468e783aa1bdb5d7252e9478866762ce80542d9
  - https://github.com/Dridi/libvmod-named/commit/9e4aa824597e886874ab947e7f99ad50968d451f

**Comment by Dridi** [comment]
:+1:
