### ISSUE TITLE
VRT_priv_task error

### ISSUE THREAD

**Issue by jansonz** [carlosabalde/libvmod-redis#33]
Hey guys,

Trying to run the Redis VMOD on Varnish 4.1.3 and getting the following VCL completion error:

Message from C-compiler:
vgc.c: In function 'VGC_function_vcl_recv':
vgc.c:2082:29: error: 'VGC_vmod_db' undeclared (first use in this function)
         VRT_priv_task(ctx, &VGC_vmod_db),
                             ^
vgc.c:2082:29: note: each undeclared identifier is reported only once for each function it appears in
vgc.c:2091:10: error: 'vmod_priv_db' undeclared (first use in this function)
         &vmod_priv_db,
          ^
Running C-compiler failed, exited with 1
VCL compilation failed

Tried to google for this and found https://www.varnish-cache.org/lists/pipermail/varnish-bugs/2015-October/007429.html

Any ideas? 

Thank you,
Janis

**Comment by carlosabalde** [comment]
Did you get this error using branch ``4.1`` or ``master``?

**Comment by jansonz** [comment]
Hey,

Master

**Comment by jansonz** [comment]
Oh, sorry. Have missed that.

Maybe would be beneficial to add that to the documentation? 😃

Thanks,
Janis
