### ISSUE TITLE
Error when install libvmod-redis

### ISSUE THREAD

**Issue by chuyenim** [carlosabalde/libvmod-redis#40]
Hello,
I can't install libvmod-redis on my VPS (Centos - Varnish 6.0.1)
In INSTALLATION setion does not have more details.
I've installed hiredis on my VPS. However I am not sure it's correct:
https://github.com/redis/hiredis

    base                                                                              | 3.6 kB  00:00:00     
    epel                                                                              | 3.2 kB  00:00:00     
    extras                                                                            | 3.4 kB  00:00:00     
    updates                                                                           | 3.4 kB  00:00:00     
    varnishcache_varnish60/x86_64/signature                                           |  836 B  00:00:00     
    varnishcache_varnish60/x86_64/signature                                           | 1.0 kB  00:00:00 !!! 
    varnishcache_varnish60-source/signature                                           |  836 B  00:00:00     
    varnishcache_varnish60-source/signature                                           | 1.0 kB  00:00:00 !!! 
    (1/2): epel/x86_64/updateinfo                                                     | 948 kB  00:00:01     
    (2/2): epel/x86_64/primary                                                        | 3.6 MB  00:00:00     
    epel                                                                                         12721/12721
    Package hiredis-0.12.1-1.el7.x86_64 already installed and latest version
    Nothing to do

My follow steps:
-- Get libvmod-redis from github
-- ``Git checkout branch 6.0``
-- ``./autogen.sh``
-- ``./configure``

Then I got these lines:

    checking whether to build shared libraries... yes
    checking whether to build static libraries... no
    checking whether to build with code coverage support... no
    ./configure: line 12079: AX_COMPILER_FLAGS_CFLAGS: command not found
    checking whether gcc is Clang... no
    checking whether pthreads work with -pthread... yes
    checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
    checking whether more special flags are required for pthreads... no
    checking for PTHREAD_PRIO_INHERIT... yes
    checking for rst2man... rst2man
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.21... yes
    checking for VARNISHAPI... yes
    checking for explicit_bzero... no
    checking for Varnish... 6.0.1
    checking vsha256.h usability... yes
    checking vsha256.h presence... yes
    checking for vsha256.h... yes
    checking cache/cache.h usability... yes
    checking cache/cache.h presence... yes
    checking for cache/cache.h... yes
    checking for a Python interpreter with version >= 2.7... python
    checking for python... /usr/bin/python
    checking for python version... 2.7
    checking for python platform... linux2
    checking for python script directory... ${prefix}/lib/python2.7/site-packages
    checking for python extension module directory... ${exec_prefix}/lib64/python2.7/site-packages
    checking for gcc option to accept ISO C99... -std=gnu99
    checking for redisCommand in -lhiredis... no
    configure: error: libvmod-redis requires libhiredis.

Please help me or give me some suggestions. Thank you in advanced

**Comment by carlosabalde** [comment]
Please, install the `hiredis-devel` and `redis` packages and try again.

**Comment by chuyenim** [comment]
> And I forgot to mention you should also install `libev` and `libev-devel`.

It works like a charm!!
Thank you very much. You saved me from pain :*

    [root@vultr lib]# redis-cli
    127.0.0.1:6379> GET foo
    "Hello world!"
    127.0.0.1:6379>

**Comment by popey456963** [comment]
Could you add this to the documentation?

**Comment by carlosabalde** [comment]
That's already documented in README.rst ➙ Installation ➙ Dependencies.

**Comment by popey456963** [comment]
I am so sorry, clearly I'm just blind, 👍
