### ISSUE TITLE
How to implement a circuit-breaker if redis is not readable 

### ISSUE THREAD

**Issue by zeug-it** [carlosabalde/libvmod-redis#42]
Hi, how to implement a circuit-breaker if the redis server is not readable or accessable?

Thanks,
Martin

**Comment by carlosabalde** [comment]
Hi. It looks like you're looking for the `.replied()` method. Form the manual page:

```
$Method BOOL .replied()

Return value
    TRUE if a previously executed Redis command using ``.execute()`` returned
    any reply. Not returning a reply usually means a failed connection, a
    connection timeout, etc.
```

If Redis Server is not readable or accesible, `.execute()` will return immediately and then you could use `.replied()` to check the error condition and jump to some fallback logic.

**Comment by zeug-it** [comment]
many thanks for the hint!
